export const data = [
  {
    no: "1",
    order_id: "#ORD0001",
    product: "Wireless Bluetooth Headphones",
    date: "01-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "2",
    order_id: "#ORD0001",
    product: "Mens T-Shirt",
    date: "02-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Pending",
    src: "/headphone.webp",
  },
  {
    no: "3",
    order_id: "#ORD0001",
    product: "Mens Leather Wallet",
    date: "03-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "4",
    order_id: "#ORD0001",
    product: "Memory Foam Pillow",
    date: "04-01-2025",
    price: "39.99",
    payment: "Paid",
    status: "Shipped",
    src: "/headphone.webp",
  },
  {
    no: "5",
    order_id: "#ORD0001",
    product: "Adjustable Dumbbells",
    date: "05-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Pending",
    src: "/headphone.webp",
  },
  {
    no: "6",
    order_id: "#ORD0001",
    product: "Coffee Maker",
    date: "06-01-2025",
    price: "79.99",
    payment: "Unpaid",
    status: "Cancelled",
    src: "/headphone.webp",
  },
  {
    no: "7",
    order_id: "#ORD0001",
    product: "Casual Baseball Cap",
    date: "07-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "8",
    order_id: "#ORD0001",
    product: "Full HD Webcam",
    date: "08-01-2025",
    price: "39.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "9",
    order_id: "#ORD0001",
    product: "Smart LED Color Bulb",
    date: "09-01-2025",
    price: "79.99",
    payment: "Unpaid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "10",
    order_id: "#ORD0001",
    product: "Mens T-Shirt",
    date: "10-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "11",
    order_id: "#ORD0001",
    product: "Wireless Bluetooth Headphones",
    date: "11-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "12",
    order_id: "#ORD0001",
    product: "Mens T-Shirt",
    date: "12-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Pending",
    src: "/headphone.webp",
  },
  {
    no: "13",
    order_id: "#ORD0001",
    product: "Mens Leather Wallet",
    date: "13-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "14",
    order_id: "#ORD0001",
    product: "Memory Foam Pillow",
    date: "14-01-2025",
    price: "39.99",
    payment: "Paid",
    status: "Shipped",
    src: "/headphone.webp",
  },
  {
    no: "15",
    order_id: "#ORD0001",
    product: "Adjustable Dumbbells",
    date: "15-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Pending",
    src: "/headphone.webp",
  },
  {
    no: "16",
    order_id: "#ORD0001",
    product: "Coffee Maker",
    date: "16-01-2025",
    price: "79.99",
    payment: "Unpaid",
    status: "Cancelled",
    src: "/headphone.webp",
  },
  {
    no: "17",
    order_id: "#ORD0001",
    product: "Casual Baseball Cap",
    date: "17-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "18",
    order_id: "#ORD0001",
    product: "Full HD Webcam",
    date: "18-01-2025",
    price: "39.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "19",
    order_id: "#ORD0001",
    product: "Smart LED Color Bulb",
    date: "19-01-2025",
    price: "79.99",
    payment: "Unpaid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "20",
    order_id: "#ORD0001",
    product: "Mens T-Shirt",
    date: "20-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Delivered",
    src: "/headphone.webp",
  },
];
