export const data = [
  {
    no: "1",
    order_id: "#ORD0001",
    product: "Wireless Bluetooth Headphones",
    date: "01-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "2",
    order_id: "#ORD0001",
    product: "Mens T-Shirt",
    date: "02-01-2025",
    price: "14.99",
    payment: "Unpaid",
    status: "Pending",
    src: "/headphone.webp",
  },
  {
    no: "3",
    order_id: "#ORD0001",
    product: "Mens Leather Wallet",
    date: "03-01-2025",
    price: "49.99",
    payment: "Paid",
    status: "Delivered",
    src: "/headphone.webp",
  },
  {
    no: "4",
    order_id: "#ORD0001",
    product: "Memory Foam Pillow",
    date: "04-01-2025",
    price: "39.99",
    payment: "Paid",
    status: "Shipped",
    src: "/headphone.webp",
  },
];
