export const bestSelling = [
  {
    id: 1,
    image: "/BestSelling/img1.svg",
    colStart: 1,
    rowStart: 1,
    colSpan: 1,
    rowSpan: 1,
    href: "/product",
  },
  {
    id: 2,
    image: "/BestSelling/img2.svg",
    colStart: 2,
    rowStart: 1,
    colSpan: 1,
    rowSpan: 1,
    href: "/product",
  },
  {
    id: 3,
    image: "/BestSelling/img3.svg",
    colStart: 3,
    rowStart: 1,
    colSpan: 1,
    rowSpan: 1,
    href: "/product",
  },
  {
    id: 4,
    image: "/BestSelling/img6.svg",
    colStart: 4,
    rowStart: 1,
    colSpan: 1,
    rowSpan: 2,
    href: "/product",
  },
  {
    id: 5,
    image: "/BestSelling/img4.svg",
    colStart: 1,
    rowStart: 2,
    colSpan: 2,
    rowSpan: 1,
    href: "/product",
  },
  {
    id: 6,
    image: "/BestSelling/img5.svg",
    colStart: 3,
    rowStart: 2,
    colSpan: 1,
    rowSpan: 1,
    href: "/product",
  },
];
