export const endpoint = {
  REGISTER: "auth/register",
  LOGIN: "auth/login",
  LOGOUT: "auth/logout",
  PRODUCT: "catalog/products",
  CATEGORY: "categories",
  FETCHCART: "cart/get",
  FETCHORDER: "orders/me",
  FETCHORDERBYID: "orders",
  ADDTOCART: "cart/add",
  DELETECART: "cart/delete",
  UPDATECART: "cart/update",
  ADD_WISHLIST: "wishlist/add",
  FETCH_WISHLIST: "wishlist",
  DELETE_WISHLIST: "wishlist/delete",
  FETCHNOTIFICATION: "notifications",
  ADDORDER: "cart/checkout-selected-items",
  ESEWAPAYMENT: "payments/esewa/initiate",
  PAYMENTSUCCESS: "payments/esewa/callback",
  NOTIFICATIONSEEN: "notifications",
  FETCHPROFILE: "profile/me",
  CHANGEPASSWORD: "auth/change_password",
  FORGOTPASSWORD: "auth/auth/forgot-password",
  VERIFYOTP: "auth/verify-otp",
  RESETPASSWORD: "auth/auth/reset-password",
  SOCIALLINKS: "profile/social-links",
  WEBSITEREVIEW: "website-reviews",
};
