export const endpoint = {
  REGISTER: "auth/register",
  LOGIN: "auth/login",
  LOGOUT: "auth/logout",
  PRODUCT: "catalog/products",
  CATEGORY: "categories",
  FETCHCART: "cart/get",
  FETCHORDER: "orders/me",
  ADDTOCART: "cart/add",
  DELETECART: "cart/delete",
  UPDATECART: "cart/update",
  ADD_WISHLIST: "wishlist/add",
  FETCH_WISHLIST: "wishlist",
  DELETE_WISHLIST: "wishlist/delete",
  FETCHNOTIFICATION: "notifications",
  ADDORDER: "orders",
  ESEWAPAYMENT: "payments/esewa/initiate",
  PAYMENTSUCCESS: "payments/esewa/verify/success",
  NOTIFICATIONSEEN: "notifications",
};
