export const endpoint = {
  REGISTER: "auth/register",
  LOGIN: "auth/login",
  LOGOUT: "auth/logout",
  FETCH_PRODUCT: "admin/products",
  FETCH_ORDER: "admin/orders",
  FETCHORDERBYID: "admin/orders",
  CHANGEPASSWORD: "auth/change_password",
  FETCH_CATEGORY: "admin/categories",
  FETCH_PROFILE: "profile/me",
  products: "admin/products",
  CATEGORIES: "admin/categories",
  REPORT: "admin/reports",
  VENDOR: "admin/vendors",
  USER: "admin/user",
  DELETE_USER: "admin/user/delete",
  UPDATE_USER: "admin/user/update",
  FORGOT_PASSWORD: "auth/forgot-password",
  VERIFY_OTP: "auth/verify-otp",
  RESET_PASSWORD: "auth/reset-password",
  SOCIALLINKS: "profile/social-links",
  ATTRIBUTES: "admin/attributes",
  TAGS: "admin/tags",
  PRODUCTTAGS: "admin/products",
};
