#!/bin/sh

cd "$(dirname "$0")/.."

dotnet restore ecommerce/backend/EcommerceProject/EcommerceProject.csproj || exit 1
dotnet build ecommerce/backend/EcommerceProject/EcommerceProject.csproj || exit 1