export const data = [
  {
    productId: "p001",
    name: "Wireless Headphones",
    status: "Featured",
    createdAt: "2025-01-05",
    order: 1,
    image: "/CategoryImage/beauty.webp",
    category: "Electronic",
  },
  {
    productId: "p002",
    name: "Smartwatch Pro X",
    status: "On sale",
    createdAt: "2025-01-10",
    order: 2,
    image: "/CategoryImage/beauty.webp",
    category: "Electronic",
  },
  {
    productId: "p003",
    name: "Bluetooth Speaker Mini",
    status: "Out of stock",
    createdAt: "2025-01-14",
    order: 3,
    image: "/CategoryImage/beauty.webp",
    category: "Electronic",
  },
  {
    productId: "p004",
    name: "4K Action Camera",
    status: "Featured",
    createdAt: "2025-01-20",
    order: 4,
    image: "/CategoryImage/beauty.webp",
    category: "Electronic",
  },
  {
    productId: "p005",
    name: "Portable Power Bank 20000mAh",
    status: "On sale",
    createdAt: "2025-01-22",
    order: 5,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "p006",
    name: "USB-C Fast Charger",
    status: "Out of stock",
    createdAt: "2025-01-25",
    order: 6,
    image: "/CategoryImage/beauty.webp",
    category: "Electronic",
  },
  {
    productId: "c001",
    name: "Men's Cotton T-Shirt",
    category: "clothes",
    status: "featured",
    createdAt: "2025-01-05",
    order: 1,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "c002",
    name: "Women's Winter Jacket",
    category: "clothes",
    status: "on_sale",
    createdAt: "2025-01-07",
    order: 2,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "c003",
    name: "Kids' Denim Jeans",
    category: "clothes",
    status: "out_of_stock",
    createdAt: "2025-01-10",
    order: 3,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "c004",
    name: "Men's Hoodie",
    category: "clothes",
    status: "featured",
    createdAt: "2025-01-12",
    order: 4,
    image: "/CategoryImage/beauty.webp",
  },

  {
    productId: "g001",
    name: "Organic Brown Rice (5kg)",
    category: "grocery",
    status: "On sale",
    createdAt: "2025-01-15",
    order: 5,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "g002",
    name: "Fresh Cow Milk (1L)",
    category: "grocery",
    status: "Featured",
    createdAt: "2025-01-17",
    order: 6,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "g003",
    name: "Organic Eggs (12 Pcs)",
    category: "grocery",
    status: "Out of stock",
    createdAt: "2025-01-20",
    order: 7,
    image: "/CategoryImage/beauty.webp",
  },
  {
    productId: "g004",
    name: "Vegetable Oil (2L)",
    category: "grocery",
    status: "On sale",
    createdAt: "2025-01-22",
    order: 8,
    image: "/CategoryImage/beauty.webp",
  },
];
